#!/usr/bin/env python3
"""Regenerate the Android adaptive launcher icon (foreground + background).

Draws the brand calendar + thumbtack as a TRANSPARENT foreground, centered on the
card (the visual anchor) and sized into the adaptive safe zone so launchers don't
zoom-clip the tabs/pin, then writes both adaptive-icon layers:

  app/src/main/res/mipmap-<dpi>/ic_launcher_foreground.png   (per density)
  app/src/main/res/drawable/ic_launcher_background.xml        (orange gradient)

The adaptive-icon XMLs in mipmap-anydpi-v26/ reference these two layers.
Run:  python tools/generate_app_icon.py     (requires Pillow:  pip install pillow)
"""
from pathlib import Path
import math
from PIL import Image, ImageDraw

RES = Path(__file__).resolve().parents[1] / "app" / "src" / "main" / "res"
REPO = RES.parents[3]
DENS = {"mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324, "xxxhdpi": 432}
SS = 4                # supersample for crisp edges
TARGET_R = 0.31       # farthest art point sits at 31% of the canvas from center (inside safe zone)

# Brand palette (design/DESIGN.md §1)
CARD = (252, 251, 248, 255); INK = (34, 28, 21, 255); ORANGE = (224, 127, 44, 255)
GREY = (214, 216, 220, 255); DIV = (236, 233, 226, 255)
GRAD_TOP, GRAD_BOT = "#F8BC63", "#E07F2C"
CARD_RECT = (45, 255, 800, 920)   # logical (1024) coords; its center is the optical anchor


def draw_art():
    C = 1024 * SS
    im = Image.new("RGBA", (C, C), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    def R(x0, y0, x1, y1, r, fill):
        d.rounded_rectangle([x0 * SS, y0 * SS, x1 * SS, y1 * SS], radius=r * SS, fill=fill)
    def E(cx, cy, rad, fill):
        d.ellipse([(cx - rad) * SS, (cy - rad) * SS, (cx + rad) * SS, (cy + rad) * SS], fill=fill)
    R(250, 150, 320, 330, 35, INK); R(430, 150, 500, 330, 35, INK)    # binder tabs
    R(*CARD_RECT, 104, CARD)                                          # card
    R(120, 372, 725, 384, 6, DIV)                                     # header divider
    R(120, 432, 725, 512, 40, ORANGE)                                 # "this week" row
    R(120, 575, 725, 650, 37, GREY); R(120, 715, 480, 790, 37, GREY)  # two grey rows
    E(778, 250, 132, INK); E(778, 250, 54, ORANGE)                    # thumbtack
    hl = Image.new("RGBA", (C, C), (0, 0, 0, 0))
    ImageDraw.Draw(hl).ellipse([(728 - 30) * SS, (212 - 30) * SS, (728 + 30) * SS, (212 + 30) * SS],
                               fill=(255, 255, 255, 130))             # tack highlight
    return Image.alpha_composite(im, hl)


def write_foreground():
    art = draw_art()
    cardC = ((CARD_RECT[0] + CARD_RECT[2]) / 2 * SS, (CARD_RECT[1] + CARD_RECT[3]) / 2 * SS)
    bx = art.getbbox()
    maxd = max(math.hypot(x - cardC[0], y - cardC[1]) for x in (bx[0], bx[2]) for y in (bx[1], bx[3]))
    for dn, F in DENS.items():
        k = (TARGET_R * F) / maxd
        rs = art.resize((round(art.width * k), round(art.height * k)), Image.LANCZOS)
        canvas = Image.new("RGBA", (F, F), (0, 0, 0, 0))
        canvas.paste(rs, (round(F / 2 - cardC[0] * k), round(F / 2 - cardC[1] * k)), rs)
        out = RES / f"mipmap-{dn}" / "ic_launcher_foreground.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        canvas.save(out)
        print("fg ->", out.relative_to(REPO))


def write_background():
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Adaptive-icon background: brand orange gradient (design/DESIGN.md §1).
     Generated by tools/generate_app_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108H0z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="6" android:startY="6"
                android:endX="102" android:endY="102"
                android:startColor="{GRAD_TOP}"
                android:endColor="{GRAD_BOT}" />
        </aapt:attr>
    </path>
</vector>
'''
    out = RES / "drawable" / "ic_launcher_background.xml"
    out.write_text(xml, encoding="utf-8")
    print("bg ->", out.relative_to(REPO))


if __name__ == "__main__":
    write_foreground()
    write_background()
    print("done — rebuild the app to pick up the new launcher icon")
